### ISSUE TITLE
Users with default image return /media/unity-128.png instead of full URL for Image_Url

### ISSUE THREAD

**Issue by Coca162** [SpikeViper/SpookVooper.Api#10]
https://github.com/SpikeViper/SpookVooper.Api/blob/77d04ce60427f230da7fb751d6dabe455f726d28/SpookVooper.Api/SpookVooperAPI.cs#L42
Should probably be changed to add the https://spookvooper.com at the start of the Image_Url

**Comment by SpikeViper** [comment]
Issue is closed
