### ISSUE TITLE
get discord roles returns list of empty dicts

### ISSUE THREAD

**Issue by asdia0** [SpikeViper/SpookVooper.Api#20]
https://api.spookvooper.com/User/GetDiscordRoles?SVID=u-1f4795a7-82f7-45bc-badd-84b50deb50f9 returns `[{},{},{},{},{},{},{},{},{},{}]` which isnt epic

**Comment by SpikeViper** [comment]
Those are actually just empty objects, but I will find the root cause & fix

**Comment by SpikeViper** [comment]
Closed in ad8a98c285c01388d00073d99a3ca7807ca2428a

**Comment by SpikeViper** [comment]
Nuget package reflects change in 1.2.7
